---
title: "p8105_hw2_lz2951"
author: "lz2951"
date: "2023-10-04"
output: github_document
---

## Library required packages

```{r}
library(tidyverse)
```

# Problem 1

## Clean the data in pols-month.csv

```{r}
pols_month = 
  read_csv(file = "./data/pols-month.csv") |> 
  janitor::clean_names() |>
  separate(mon, into = c("year", "month", "day"), sep = "-", convert = TRUE) |>
  mutate(
    month = case_match(
      month,
      1 ~ "January",
      2 ~ "February",
      3 ~ "March",
      4 ~ "April",
      5 ~ "May",
      6 ~ "June",
      7 ~ "July",
      8 ~ "August",
      9 ~ "September",
      10 ~ "October",
      11 ~ "November",
      12 ~ "December"
    )
  ) |>
  pivot_longer(
    c("prez_dem", "prez_gop"),
    names_to = "president",
    names_prefix = "prez_",
    values_to = "party"
  ) |>
  filter(party == 1) |>
  select(-party, -day)
```

## Clean the data in snp.csv

```{r}
snp = 
  read_csv(file = "./data/snp.csv", col_types = cols(date = col_date(format = "%m/%d/%y"))) |>
  janitor::clean_names() |>
  separate(date, into = c("year", "month", "day"), sep = "-", convert = TRUE) |>
  mutate(year = if_else(year > 2023, year - 100, year)) |>
  arrange(year, month) |>
  mutate(
    month = case_match(
      month,
      1 ~ "January",
      2 ~ "February",
      3 ~ "March",
      4 ~ "April",
      5 ~ "May",
      6 ~ "June",
      7 ~ "July",
      8 ~ "August",
      9 ~ "September",
      10 ~ "October",
      11 ~ "November",
      12 ~ "December"
    )
  ) |>
  select(year, month, close)
```

## Clean the unemployment data

```{r}
unemployment =
  read_csv(file = "./data/unemployment.csv") |>
  janitor::clean_names() |>
  pivot_longer(
    jan:dec,
    names_to = "month",
    values_to = "unemployment"
  ) |>
  mutate(
    month = case_match(
      month,
      "jan" ~ "January",
      "feb" ~ "February",
      "mar" ~ "March",
      "apr" ~ "April",
      "may" ~ "May",
      "jun" ~ "June",
      "jul" ~ "July",
      "aug" ~ "August",
      "sep" ~ "September",
      "oct" ~ "October",
      "nov" ~ "November",
      "dec" ~ "December"
    )
  )
```

## Merge three datasets

```{r}
complete_df =
  left_join(pols_month, snp, join_by("year", "month")) |>
  left_join(unemployment, join_by("year", "month"))
```


